# Generated by Django 5.1.5 on 2025-01-15 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='country',
            new_name='address_country',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='state',
            new_name='address_state',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='borrower_birth_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='interest_rate',
            new_name='contract_rate',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='disbursed_amount',
            new_name='loan_value',
        ),
        migrations.AlterField(
            model_name='contract',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.IntegerField()),
                ('parcel_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='contracts.contract')),
            ],
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
